### ISSUE TITLE
Przejrzeć pr od botów 

### ISSUE THREAD

**Issue by m87** [Consdata/sonarqube-companion#102]
Trochę pr od snyka i dependentbota wpadło. Imo trzeba ja przejrzeć i zmergować, bo po to są chyba podpięte :)

**Comment by glipecki** [comment]
podbiję liby, zobaczę czy działa i wrzucę. powinno zamknąć większość prków od botów.

**Comment by glipecki** [comment]
poczyszczone, zobaczymy co wpadnie nowego i podejdziemy indywidualnie.
