### ISSUE TITLE
[support] the Setting Page problem"Insufficient authentication parameters"

### ISSUE THREAD

**Issue by ontheway01** [Consdata/sonarqube-companion#169]
Thanks for this project.I can get different groups information.
I have encountered some problems while using the project.
Firstly，I started with docker run with `docker run -p 8000:8080 consdata/sonarqube-companion:latest`.
Secondly,When I setted the Servers ​,it came with the error-- In`sufficient authentication parameters
`.I have changed the Authorization method from token to basic，but it was Still the same error.
![error](https://github.com/ontheway01/flask_blog/blob/master/%E6%88%AA%E5%B1%8F2021-08-25%20%E4%B8%8B%E5%8D%8811.15.29.png?raw=true)
running log as below:
> INFO 7 --- [nio-8080-exec-7] p.c.i.s.c.s.g.s.ServerConfigService : Invalid server definition ServerDefinition(id=localsonarqube, uuid=8930e274-4c64-47ec-afeb-0fb6f7d61375, url=http://localhost:9000/, authentication=ServerAuthentication(type=token, params={}), blacklistUsers=[], aliases=null) reason: ValidationResult(message=Insufficient authentication parameters, code=AUTH_CONSTRAINT, valid=false

**Comment by m87** [comment]
Thanks for report! We're currently working on new version of the app. Meanwhile you can mount this basic config. 

```json
{
  "servers" : [ {
    "id" : "http://localhost:9000/",
    "uuid" : "http://localhost:9000/",
    "url" : "http://localhost:9000/",
    "authentication" : {
      "type" : "token",
      "params" : {
        "token" : "token1"
      }
    },
    "blacklistUsers" : [ ],
    "aliases" : [ ]
  } ],
  "rootGroup" : {
    "uuid" : "3e05faec-3abd-4236-be34-addf47e858e6",
    "name" : "All projects",
    "description" : null,
    "groups" : [ ],
    "projectLinks" : [ ],
    "events" : [ ],
    "webhooks" : [ ],
    "members" : [ ]
  },
  "scheduler" : {
    "interval" : 1,
    "timeUnit" : "DAYS"
  },
  "members" : {
    "local" : [ ],
    "recursive" : false
  },
  "integrations" : null
}
```
```bash
docker run -v /PATH_TO_INITIAL_CONFIG:/opt/sonarqube-companion/repository/sq-companion-config.json -p 8000:8080 consdata/sonarqube-companion:latest
```

With this config you should be able to modify settings from ui level.
